[package]
name = "glob_match"
description = "An extremely fast glob matcher"
version = "0.2.1"
license = "MIT"
authors = ["Devon Govett <devongovett@gmail.com>", "dalaoshu <laipichan@qq.com>"]
edition = "2021"

[dev-dependencies]
criterion = "0.4.0"
glob = "0.3.1"
globset = "0.4.10"

[[bench]]
name = "bench"
harness = false

[[test]]
name = "basic_test"
path = "tests/basic.rs"

[profile.release]
lto = true
codegen-units = 1
panic = 'abort'
