name: CodSpeed

permissions: {}

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: oxc-project/setup-rust@d286d43bc1f606abbd98096666ff8be68c8d5f57 # v1.0.2
        with:
          cache-key: benchmark
          save-cache: ${{ github.ref_name == 'main' }}
          tools: cargo-codspeed

      - run: cargo codspeed build

      - uses: CodSpeedHQ/action@653fdc30e6c40ffd9739e40c8a0576f4f4523ca1 # v4.0.1
        with:
          run: cargo codspeed run
          token: ${{ secrets.CODSPEED_TOKEN }}
